### ISSUE TITLE
Does your code work well?

### ISSUE THREAD

**Issue by mo666666** [yuanzhi-zhu/mini_edm#1]
Hello, yuanzhi. Thank you for your excellent code. Do you try to run it? What FID can we finally obtained?

**Comment by yuanzhi-zhu** [comment]
Hi Yichuan, thank you for your interest.
unfortunately, I do not have enough computational resources to run the same experiments.
However I believe this implementation covers the essence of EDM, and this implementation has a similar performance to the original EDM code under the same setting (e.g. #parameters).
![image_200000](https://github.com/yuanzhi-zhu/mini_edm/assets/24802044/a3e9087e-063d-44d6-a1be-622743c5434e)
cheers,

**Comment by mo666666** [comment]
Wow, that's cool!!! I would recommend using EMA to improve the quality of generated images. It seems that it can help a lot when training the diffusion models. Thank you again for sharing the codes with the community!

**Comment by yuanzhi-zhu** [comment]
Thanks for the reminder.
Indeed, the images generated by the ema model from the original model are not so good :(
Maybe I have to tune some hyper-parameters.
Will let you know if I make it work xD

**Comment by yuanzhi-zhu** [comment]
@mo666666 hi Yichuan, the code should work the same as edm now 🤣 
15M parameters, 150k steps with bs of 128 (~13h on single 2080ti); the fid is 6.364170
![image_ema_150000](https://github.com/yuanzhi-zhu/mini_edm/assets/24802044/9c64c056-cd60-413e-ad43-65b79fffab24)

**Comment by mo666666** [comment]
The quality of the generated images seems good. Do you calculate the FID of the generated images? By the way,  If convenient for you, we can further communicate through WeChat.
