### ISSUE TITLE
networks_edm.py confusion

### ISSUE THREAD

**Issue by diffusionstudent** [yuanzhi-zhu/mini_edm#2]
Hi,

First thank you so much for this repo, this is super helpful for me to understand a lot of important details about the paper!

I found one thing a little bit confusing to me. In the networks_edm.py, line 177 wrote like this way:
q, k, v = self.qkv(self.norm2(x)).reshape(x.shape[0] * self.num_heads, x.shape[1] // self.num_heads, 3, -1).unbind(2)

It seems like the multi-head split is happening on the sequence_length dimension instead of the model_dim dimension, maybe I am just too stupid to understand, or this is a special design from somewhere.

Could you please elaborate a little bit more on this issue?

Thank you in advance!

**Comment by yuanzhi-zhu** [comment]
I am not sure, this file is copy-pasted directly from the original EDM repository.

However, we can make a test.
with `x.shape = torch.Size([128, 192, 16, 16])` and a `num_heads=4`, after the calculation in line 177:
`q, k, v = self.qkv(self.norm2(x)).reshape(x.shape[0] * self.num_heads, x.shape[1] // self.num_heads, 3, -1).unbind(2)`
we have `q.shape = k.shape = v.shape = torch.Size([512, 48, 256])`, where 48 is the feature channel number and 256=16*16 is the spatial tokens (feature pixels?). Which means the multi-head split is happening on the model_dim dimension?

Then `w = AttentionOp.apply(q, k)` returns a tensor w with shape torch.Size([512, 256, 256]), which should be the attention weight between spatial tokens or let's say the attention within pixels in current resolution in the Unet.

Please correct me if I got it wrong.

**Comment by diffusionstudent** [comment]
Hi Yuanzhi,
 
Thank you for your quick reply! I think you are correct, as I misunderstood the actions behind the AttentionOp class, I thought the second dimension is the sequence length dimension, I didn't check the einsum operation very carefully, I am really sorry for wasting your time.

Also, as you have mentioned in this repo's name, a "minimalistic" implementation of the edm paper, as i understand this repo implemented literally everything in the edm paper, may I ask is the only difference between this implementation and their implementation the dataset? I think they also trained their model on ImageNet, but that would be too resource expensive.

**Comment by yuanzhi-zhu** [comment]
You are right, the repo now contains the essence of EDM :p 
I have to admit that this code is easy to tune only at a small scale.
After getting a feeling of the components and hyperparameters people should switch to the official repo for their own expr...

**Comment by diffusionstudent** [comment]
Well that requires a lot for a nice GPU then :)

By the way i saw in another already closed issue you are using a 2080 for your experiment, if you need some free computation resources you can just contact me, sometimes we have some 4090s and 3060s sitting in our uni doing nothing:) 

Thank you for your clarification, I wish you have a very nice night!

**Comment by yuanzhi-zhu** [comment]
Thank you so much for that.
Currently I have some 3090 at hand and are enough for me
